'''
This is the main script that has to be executed.
Includes all the Snakefiles needed to execute the workflow.
'''

#Configuration yaml.
configfile: "config/config.yaml"


#Global variables
data_dir = config["data_dir"]
results_dir = config["results_dir"]
# barcodes = config["barcodes.txt"]
ref_genome = config["ref_genome"]
ref_genome_ext = config["ref_genome_ext"]
sample_name = config["sample_name"]
sample_ext = config["sample_ext"]


#Included rules
include: "Rules/Fasta.smk"
include: "Rules/Mapping.smk"
include: "Rules/Trimming.smk"
include: "Rules/Variant-calling.smk"
include: "Rules/Graph_plotting.smk"


#Output is the variant file and the plotted variants.
rule all:
    input:
        f"{results_dir}/pileups/{sample_name}.pileup.vcf",
        f"{results_dir}/variants.png"
