data_dir: /students/2023-2024/Thema11/dhaandrikman_snakemake/data
results_dir: /students/2023-2024/Thema11/dhaandrikman_snakemake/results
ref_genome: GCF_000001405.40_GRCh38.p14_genomic
ref_genome_ext: .fa
sample_name: ERR5433940
sample_ext: .fastq
type_of_sequence: paired
adaptor_sequence: ""
output_file_name: variants.vcf
